Repository thinknimble/tn-spa-bootstrapper, pull requests merged in 2023-01, with the labels that each got.

#137 Add a JSON Web Token Authentication class for DRF
  hooks/post_gen_project.py
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/core/jwt_auth.py
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/settings.py
Labels: Ready For Review

#144 Fix/Vue3 landmark WCAG fixes
  {{cookiecutter.project_slug}}/clients/vue3/public/index.html
  {{cookiecutter.project_slug}}/clients/vue3/src/App.vue
  {{cookiecutter.project_slug}}/clients/vue3/src/views/Dashboard.vue
Labels: Ready For Review

#138 updated aws-configs
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/settings.py
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/test_settings.py
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/utils/storages.py
Labels: Ready For Review

#107 React client - Improve TS in auth.tsx, remove potential memory leak
  {{cookiecutter.project_slug}}/clients/react/.env.local.example
  {{cookiecutter.project_slug}}/clients/react/src/utils/auth.tsx
Labels: Help Wanted, Ready For Review

#136 React Client - Tn forms utils
  {{cookiecutter.project_slug}}/clients/react/README.md
  {{cookiecutter.project_slug}}/clients/react/package.json
  {{cookiecutter.project_slug}}/clients/react/src/forms/index.ts
  {{cookiecutter.project_slug}}/clients/react/src/forms/login.ts
  {{cookiecutter.project_slug}}/clients/react/src/forms/signup.ts
  {{cookiecutter.project_slug}}/clients/react/src/pages/LogIn.tsx
  {{cookiecutter.project_slug}}/clients/react/src/pages/SignUp.tsx
  {{cookiecutter.project_slug}}/clients/react/src/utils/queries.ts
Labels: DO NOT MERGE, In Progress

#145 Improvement/update tests
  .github/workflows/pytest.yml
  {{cookiecutter.project_slug}}/.env.example
  {{cookiecutter.project_slug}}/.github/workflows/pytest.yml
  {{cookiecutter.project_slug}}/Pipfile
  {{cookiecutter.project_slug}}/pytest.ini
  {{cookiecutter.project_slug}}/scripts/init-db.sh
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/core/factories.py
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/core/tests.py
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/test_settings.py
Labels: In Progress

#146 isort ignore migration files
  {{cookiecutter.project_slug}}/pyproject.toml
Labels: Ready For Review

#149 cookiecutter template for swagger
  {{cookiecutter.project_slug}}/server/{{cookiecutter.project_slug}}/common/urls.py
Labels: Ready For Review, clean up
