Repository thinknimble/tn-spa-bootstrapper, pull requests merged in 2024-03, with the labels that each got.

#283 update GH Actions for mobile remove sentry vars
  {{cookiecutter.project_slug}}/.github/workflows/expo-main.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-pr.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-teststore-build-android.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-teststore-build-ios.yml
  {{cookiecutter.project_slug}}/clients/mobile/react-native/Config.js
  {{cookiecutter.project_slug}}/clients/mobile/react-native/app.config.js
  {{cookiecutter.project_slug}}/clients/mobile/react-native/eas.json
Labels: Ready For Review

#285 Mobile - Remove yarn from expo gh actions. Use NPM
  {{cookiecutter.project_slug}}/.github/workflows/expo-emergency-prod-update.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-main.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-pr.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-teststore-build-android.yml
  {{cookiecutter.project_slug}}/.github/workflows/expo-teststore-build-ios.yml
Labels: Ready For Review

#286 Refactor - Mobile - Remove irrelevant services context
  {{cookiecutter.project_slug}}/clients/mobile/react-native/App.tsx
  {{cookiecutter.project_slug}}/clients/mobile/react-native/README.md
  {{cookiecutter.project_slug}}/clients/mobile/react-native/package.json
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/screens/auth/login.tsx
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/screens/auth/sign-up.tsx
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/screens/dashboard.tsx
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/screens/index.ts
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/screens/routes.ts
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/services/index.tsx
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/services/onStart.ts
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/services/translate/index.ts
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/services/translate/translations.ts
  {{cookiecutter.project_slug}}/clients/mobile/react-native/src/utils/providers.tsx
Labels: Ready For Review

#294 remove\ typings from bs
  {{cookiecutter.project_slug}}/clients/mobile/react-native/global.d.ts
  {{cookiecutter.project_slug}}/clients/mobile/react-native/nativewind-env.d.ts
Labels: clean up

#295 new way of env vars
  {{cookiecutter.project_slug}}/clients/mobile/react-native/.env.example
  {{cookiecutter.project_slug}}/clients/mobile/react-native/Config.js
  {{cookiecutter.project_slug}}/clients/mobile/react-native/babel.config.js
  {{cookiecutter.project_slug}}/clients/mobile/react-native/package.json
Labels: Ready For Review, mobile
